services:
  postgres:
    image: postgres:15-alpine
    container_name: stationflow-db
    environment:
      POSTGRES_DB: stationflowdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stationflow-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: stationflow-backend
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/stationflowdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx400m"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - stationflow-network

  frontend:
    build: ./Frontend
    container_name: stationflow-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - stationflow-network

volumes:
  postgres_data:


networks:
  stationflow-network:
    driver: bridge
